services:
  mindmap-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    container_name: mindmap-app
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development