# ハイパーパラメータ設定
training:
  # 基本設定
  num_episodes: 10000
  batch_size: 32
  learning_rate: 0.0003
  gamma: 0.99
  
  # DQN設定
  dqn:
    buffer_size: 100000
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995
    target_update_freq: 100
    
  # PPO設定
  ppo:
    n_steps: 2048
    n_epochs: 10
    clip_range: 0.2
    vf_coef: 0.5
    ent_coef: 0.01
    
  # 学習率スケジューリング
  lr_scheduler:
    enabled: true
    type: "exponential"
    decay_rate: 0.99
    decay_steps: 1000
    
model:
  # ネットワークアーキテクチャ
  hidden_sizes: [256, 128, 64]
  activation: "relu"
  dropout: 0.1
  
  # 2D最適化
  use_cnn: false  # 2D空間なので不要
  embedding_dim: 32
  
optimization:
  # Optuna設定
  n_trials: 50
  timeout: 3600  # 秒
  sampler: "TPESampler"
  pruner: "MedianPruner"
  
  # 探索空間
  search_space:
    learning_rate: [0.00001, 0.01]
    batch_size: [16, 128]
    gamma: [0.9, 0.999]
    hidden_sizes: [[128, 64], [256, 128], [512, 256, 128]]