# ユース部門専用設定
agent:
  type: "hybrid"  # rule_based, ml_agent, hybrid
  ml_weight: 0.7
  rule_weight: 0.3
  
  # 2D空間専用設定
  dimension: 2
  coordinate_system: "cartesian"
  
  # 完全観測活用設定
  use_full_observation: true
  prediction_horizon: 0  # 予測不要
  
tactics:
  default: "balanced"
  available:
    - "aggressive"
    - "defensive"
    - "balanced"
    - "escort_priority"
  switch_threshold: 0.3
  
  # 編隊戦術
  formation:
    enabled: true
    types:
      - "diamond"
      - "line"
      - "wedge"
      - "circle"
    
performance:
  # 制限値に対する安全マージン
  max_step_time: 2.5  # 3秒制限に対して
  memory_limit_mb: 7000  # 7.5GB制限に対して
  
  # 最適化設定
  use_jit: true
  batch_processing: true
  parallel_evaluation: false
  
reward:
  # 報酬重み
  weights:
    enemy_destroyed: 100.0
    escort_survived: 200.0
    own_survived: 50.0
    distance_to_enemy: -0.1
    formation_bonus: 10.0
    time_penalty: -0.01