version: '3.8'

services:
  mindmap:
    build: .
    container_name: mindmap-app
    ports:
      - "3000:5173"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true