# Project configuration for Mitsui Commodity Prediction Challenge

# Competition settings
competition:
  name: "mitsui-commodity-prediction-challenge"
  metric: "custom_sharpe_ratio"
  submission_limit_per_day: 5
  final_submission_selection: 2

# Data paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  features: "data/features"
  models: "models"
  submissions: "submissions"
  logs: "logs"

# Data settings
data:
  train_file: "train.csv"
  test_file: "test.csv"
  sample_submission: "sample_submission.csv"
  date_column: "date"
  target_column: "target"
  id_column: "id"

# Feature engineering
features:
  # Moving averages
  ma_windows: [7, 14, 30, 60, 90]
  
  # Rolling statistics
  rolling_windows: [7, 14, 30]
  rolling_stats: ["mean", "std", "min", "max", "median"]
  
  # Lag features
  lag_periods: [1, 2, 3, 5, 7, 14, 30]
  
  # Technical indicators
  use_technical_indicators: true
  
  # External features
  use_external_data: true

# Model settings
model:
  # Random state for reproducibility
  random_state: 42
  
  # Cross-validation
  cv_folds: 5
  cv_strategy: "TimeSeriesSplit"
  
  # Model types
  models_to_train:
    - "lightgbm"
    - "xgboost"
    - "catboost"
    - "ensemble"
  
  # LightGBM parameters
  lightgbm:
    objective: "regression"
    metric: "rmse"
    n_estimators: 1000
    learning_rate: 0.01
    num_leaves: 31
    max_depth: -1
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.1
    early_stopping_rounds: 100
    verbose: -1
  
  # XGBoost parameters
  xgboost:
    objective: "reg:squarederror"
    eval_metric: "rmse"
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 6
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    early_stopping_rounds: 100
    verbosity: 0
  
  # CatBoost parameters
  catboost:
    loss_function: "RMSE"
    eval_metric: "RMSE"
    iterations: 1000
    learning_rate: 0.01
    depth: 6
    l2_leaf_reg: 3.0
    subsample: 0.8
    colsample_bylevel: 0.8
    early_stopping_rounds: 100
    verbose: false

# Hyperparameter optimization
optimization:
  use_optuna: true
  n_trials: 100
  optimization_metric: "rmse"
  timeout: 3600  # seconds

# Training settings
training:
  use_gpu: false
  n_jobs: -1
  max_memory_gb: 8
  batch_size: 1024
  patience: 10

# Ensemble settings
ensemble:
  method: "weighted_average"  # Options: "simple_average", "weighted_average", "stacking"
  weights_optimization: true
  meta_model: "ridge"  # For stacking

# Experiment tracking
tracking:
  use_mlflow: false
  use_wandb: false
  experiment_name: "mitsui-commodity-prediction"
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"

# Validation
validation:
  holdout_size: 0.2
  use_time_based_split: true
  gap_days: 0  # Gap between train and validation

# Post-processing
post_processing:
  clip_predictions: true
  clip_percentile: [1, 99]
  smooth_predictions: false
  smoothing_window: 3